name = "Los Pibes del Fondo 2025"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69a4d45351207316cc550d2ab010bde38a591f32d753beeeeb7d4517e339725d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
