enablePinning = true
keepCentered = false
settingsButton = true
enableBook = false

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = true
enabled = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
